### PR TITLE
refactor: move browser specific logic to conditionally run and enable ssr again

### PR DESCRIPTION
**Pull request by 0xecho**
Tried starting this locally but ssr was causing issues (specifically localStorage being access on the server side where it is only apart of the browser API). 
This PR enables site wide ssr again and conditionally use browser specific functions only in the browser

### CODE REVIEW

**Comment by frectonz** [comment]
Thanks for the PR really appreciate your interest and congrats for creating the first trantor PR 🎉 😂

SSR is disabled for a reason, the client website is meant to be a CSR web app, because it's built and directly embedded in the trantor binary. This is meant to streamline the deployment process so instead of deploying two services (the client website and the server) you will only need to deploy the single binary which has the frontend files embedded within it.

**Comment by 0xecho** [comment]
Thanks mate, glad to have the honor of first blood!
That makes sense yes. I haven't checked the rust side well (because of obvs reasons) so I'm not sure how the static files are being served. Is there any other reason apart from the DX for this?  What I'm trying to get at is containerizing the app could give the same benefits DX, wise, while also decoupling both halves. Plus adding a reverse proxy might also yield better caching support for the static files but not totally sure on this because I have no clue how its working with the rust rn 😅.

**Comment by frectonz** [comment]
I don't want containerization to be the main way to deploy trantor. Here is how i expect most people will use it

1. Download the `trantor` binary from the github releases
2. `scp` the binary to a VPS
3. initialize the `systemd` config
4. `systemctl start trantor` 
5. Celebrate 🎉

If you know about [pocketbase](https://pocketbase.io/) think of trantor as an analytics server that follows the single binary and deployability standards of pocketbase. The static client files are embedded in the `trantor` binary file in the same vein as `pocketbase`'s dashboard is embeded in the `pocketbase` binary file. The main reason for doing this is making the deployment process very easy, you would only need to `scp` a single binary on to your server.

And for caching there are already some rudimentary caching headers already being used in the server, like `last-modified` and `cache-control`. Which i think are enough for although i will probably replace `last-modified` with `Etag`. I think this caching mechanisms are enough since **trantor** is not meant to be a SaaS tool that multiple users are going to be visiting. The dashboard will only be accessible to the users of that single deployment.

**Comment by frectonz** [comment]
There are some more interesting parts in this PR, besides enabling SSR so i have decide to merge the changes, and revert some of the unneeded stuff. 

Thanks for spending your time working on **Trantor**

**Comment by frectonz** [comment]
@all-contributors please add @0xecho for code

**Comment by frectonz** [comment]
@all-contributors please add @frectonz for code

**Pull request merged**
